using System.Globalization;
using System.IO.Compression;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using DKay.GameServerDock.Application.Abstractions;
using DKay.GameServerDock.Application.Models;
using DKay.GameServerDock.Domain;
using DKay.GameServerDock.Infrastructure.Installation;

namespace DKay.GameServerDock.Infrastructure.Games;

public sealed partial class Cs2ModeManager(HttpClient httpClient) : ICs2ModeManager
{
    private const long MaximumDownloadBytes = 256L * 1024 * 1024;
    private static readonly JsonSerializerOptions FileJsonOptions = new(JsonSerializerDefaults.Web) { WriteIndented = true };
    private static readonly IReadOnlyDictionary<string, PackageSource> PackageSources =
        new Dictionary<string, PackageSource>(StringComparer.Ordinal)
        {
            ["metamod-source"] = new(PackageSourceKind.MetamodSnapshot, null),
            ["counterstrikesharp"] = new(PackageSourceKind.GitHubRelease, "roflmuffin/CounterStrikeSharp"),
            ["cs2-tags"] = new(PackageSourceKind.GitHubRelease, "daffyyyy/CS2-Tags"),
            ["movement-unlocker"] = new(PackageSourceKind.GitHubRelease, "Source2ZE/MovementUnlocker"),
            ["rampbug-fix"] = new(PackageSourceKind.GitHubRelease, "Interesting-exe/CS2Fixes-RampbugFix"),
            ["sharp-timer"] = new(PackageSourceKind.GitHubRelease, "Letaryat/poor-sharptimer"),
            ["cs2kz"] = new(PackageSourceKind.GitHubRelease, "KZGlobalTeam/cs2kz-metamod")
        };

    public IReadOnlyList<Cs2ModePresetDescriptor> Presets => Cs2ModeCatalog.Presets;
    public IReadOnlyList<Cs2ManagedPackageDescriptor> Packages => Cs2ModeCatalog.Packages;

    public Cs2ModeProfile? GetActiveProfile(GameServerInstance server)
    {
        var document = ReadModeDocument(server);
        var profile = document.ActiveProfileId is null
            ? null
            : document.Profiles.FirstOrDefault(profile => profile.Id == document.ActiveProfileId);
        if (profile is null)
        {
            return null;
        }

        try
        {
            Cs2ModeCatalog.ValidateMap(profile.MapName, profile.WorkshopId);
            return profile;
        }
        catch (ArgumentException)
        {
            return null;
        }
    }

    public Task<Cs2ModeState> GetStateAsync(GameServerInstance server, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return Task.FromResult(BuildState(server, ReadModeDocument(server)));
    }

    public async Task<Cs2ModeState> ApplyPresetAsync(
        GameServerInstance server,
        ApplyCs2ModePresetRequest request,
        CancellationToken cancellationToken)
    {
        var preset = Presets.FirstOrDefault(item => string.Equals(item.Id, request.PresetId, StringComparison.Ordinal))
            ?? throw new ArgumentException($"Unknown CS2 preset '{request.PresetId}'.");
        var convars = Cs2ModeCatalog.BuildConVars(preset, request);
        var mapName = request.MapName.Trim();
        var workshopId = string.IsNullOrWhiteSpace(request.WorkshopId) ? null : request.WorkshopId.Trim();
        var profileId = workshopId is null ? mapName.ToLowerInvariant() : $"workshop-{workshopId}";
        var normalizedOverrides = (request.Overrides ?? new Dictionary<string, string>())
            .Where(pair => preset.Settings.Any(setting => setting.Editable && setting.Key == pair.Key))
            .ToDictionary(pair => pair.Key, pair => convars[pair.Key], StringComparer.Ordinal);
        var profile = new Cs2ModeProfile(
            profileId,
            preset.Id,
            preset.Name,
            mapName,
            workshopId,
            request.BotQuota,
            request.BotDifficulty,
            normalizedOverrides,
            preset.RecommendedPackageIds,
            DateTimeOffset.UtcNow);

        var cfgRoot = GetCfgRoot(server);
        var mapsRoot = Path.Combine(cfgRoot, "dkay", "maps");
        Directory.CreateDirectory(mapsRoot);
        var profilePath = Path.Combine(mapsRoot, $"{profileId}.cfg");
        var lines = new List<string>
        {
            "// Generated by DKay Game Server Dock. Edit the preset in the admin panel.",
            $"// Preset: {preset.Name}; map: {mapName}; generated: {profile.UpdatedAt:O}",
            "bot_kick"
        };
        lines.AddRange(convars.OrderBy(pair => pair.Key, StringComparer.Ordinal).Select(pair => $"{pair.Key} {FormatCfgValue(pair.Value)}"));
        await WriteAllLinesAtomicallyAsync(profilePath, lines, cancellationToken);
        await WriteAllLinesAtomicallyAsync(
            Path.Combine(cfgRoot, "dkay-mode.cfg"),
            [
                "// Active map preset managed by DKay Game Server Dock.",
                $"exec dkay/maps/{profileId}.cfg"
            ],
            cancellationToken);

        var document = ReadModeDocument(server);
        var profiles = document.Profiles.Where(item => item.Id != profile.Id).Append(profile).OrderBy(item => item.MapName).ToArray();
        document = new ModeDocument(profile.Id, profiles);
        await WriteJsonAtomicallyAsync(GetModeDocumentPath(server), document, cancellationToken);
        return BuildState(server, document);
    }

    public IReadOnlyList<string> ResolveAutomaticInstallOrder(IEnumerable<string> packageIds)
    {
        var result = new List<string>();
        var visiting = new HashSet<string>(StringComparer.Ordinal);
        var visited = new HashSet<string>(StringComparer.Ordinal);

        foreach (var packageId in packageIds)
        {
            Visit(packageId);
        }

        return result;

        void Visit(string packageId)
        {
            if (visited.Contains(packageId))
            {
                return;
            }

            if (!visiting.Add(packageId))
            {
                throw new InvalidOperationException("The managed package catalog contains a dependency cycle.");
            }

            var package = Packages.FirstOrDefault(item => item.Id == packageId)
                ?? throw new ArgumentException($"Unknown managed package '{packageId}'.");
            foreach (var dependency in package.DependencyIds)
            {
                Visit(dependency);
            }

            visiting.Remove(packageId);
            visited.Add(packageId);
            if (package.AutomaticInstall)
            {
                result.Add(packageId);
            }
        }
    }

    public Task RepairAfterGameUpdateAsync(GameServerInstance server, CancellationToken cancellationToken) =>
        ReadPackageMarker(server, "metamod-source").Installed
            ? PatchGameInfoAsync(server, cancellationToken)
            : Task.CompletedTask;

    public async Task InstallPackageAsync(
        GameServerInstance server,
        string packageId,
        Func<InstallationProgress, CancellationToken, Task> reportProgress,
        CancellationToken cancellationToken)
    {
        var package = Packages.FirstOrDefault(item => item.Id == packageId)
            ?? throw new ArgumentException($"Unknown managed package '{packageId}'.");
        if (!package.AutomaticInstall || !PackageSources.TryGetValue(packageId, out var source))
        {
            throw new InvalidOperationException($"'{package.Name}' has no trusted automatic installation channel.");
        }

        foreach (var dependency in package.DependencyIds)
        {
            if (!ReadPackageMarker(server, dependency).Installed)
            {
                throw new InvalidOperationException($"Install dependency '{dependency}' before '{package.Name}'.");
            }
        }

        var csgoRoot = GetCsgoRoot(server);
        if (!Directory.Exists(csgoRoot))
        {
            throw new InvalidOperationException("The CS2 installation is incomplete; the game/csgo directory is missing.");
        }

        await reportProgress(new InstallationProgress(5, "resolve", $"Resolving trusted {package.Name} release…"), cancellationToken);
        var download = source.Kind == PackageSourceKind.MetamodSnapshot
            ? await ResolveMetamodSnapshotAsync(cancellationToken)
            : await ResolveGitHubReleaseAsync(packageId, source.Repository!, cancellationToken);
        var temporaryRoot = Path.Combine(Path.GetTempPath(), $"dkay-cs2-mod-{Guid.NewGuid():N}");
        Directory.CreateDirectory(temporaryRoot);

        try
        {
            var archivePath = Path.Combine(temporaryRoot, "package.zip");
            await DownloadAsync(download.Url, archivePath, cancellationToken);
            await reportProgress(new InstallationProgress(55, "verify", $"Validating {package.Name} archive paths…"), cancellationToken);
            var stagingRoot = Path.Combine(temporaryRoot, "staging");
            await SafeZipExtractor.ExtractAsync(archivePath, stagingRoot, cancellationToken);
            var deployment = ResolveDeployment(packageId, stagingRoot, csgoRoot);
            await reportProgress(new InstallationProgress(75, "deploy", $"Deploying {package.Name} into game/csgo…"), cancellationToken);
            await CopyPayloadAsync(deployment.SourceRoot, deployment.DestinationRoot, cancellationToken);

            if (packageId == "metamod-source")
            {
                await PatchGameInfoAsync(server, cancellationToken);
            }

            await WritePackageMarkerAsync(server, new PackageMarker(true, download.Version, DateTimeOffset.UtcNow), packageId, cancellationToken);
            await reportProgress(new InstallationProgress(100, "complete", $"{package.Name} {download.Version} installed."), cancellationToken);
        }
        finally
        {
            if (Directory.Exists(temporaryRoot))
            {
                try
                {
                    Directory.Delete(temporaryRoot, true);
                }
                catch (IOException)
                {
                    // A temporary antivirus/file-indexing lock must not turn a completed install into a failure.
                }
                catch (UnauthorizedAccessException)
                {
                    // Best-effort cleanup; the OS temp cleaner can remove a locked directory later.
                }
            }
        }
    }

    private Cs2ModeState BuildState(GameServerInstance server, ModeDocument document)
    {
        var packageStates = Packages.Select(package =>
        {
            var marker = ReadPackageMarker(server, package.Id);
            return new Cs2ManagedPackageState(
                package.Id,
                package.Name,
                package.Kind,
                package.Description,
                package.Publisher,
                package.ProjectUrl,
                package.AutomaticInstall,
                package.Experimental,
                marker.Installed,
                marker.Version,
                marker.InstalledAt,
                package.DependencyIds);
        }).ToArray();
        return new Cs2ModeState(document.ActiveProfileId, document.Profiles, packageStates);
    }

    private async Task<PackageDownload> ResolveMetamodSnapshotAsync(CancellationToken cancellationToken)
    {
        var platform = OperatingSystem.IsWindows() ? "windows" : "linux";
        var latestUrl = new Uri($"https://mms.alliedmods.net/mmsdrop/2.0/mmsource-latest-{platform}");
        using var response = await SendTrustedAsync(latestUrl, cancellationToken);
        var fileName = (await response.Content.ReadAsStringAsync(cancellationToken)).Trim();
        if (!MetamodFilePattern().IsMatch(fileName) || !fileName.EndsWith($"-{platform}.zip", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("AlliedModders returned an unexpected Metamod snapshot name.");
        }

        var suffix = $"-{platform}.zip";
        var version = fileName["mmsource-".Length..^suffix.Length];
        return new PackageDownload(new Uri($"https://mms.alliedmods.net/mmsdrop/2.0/{fileName}"), version);
    }

    private async Task<PackageDownload> ResolveGitHubReleaseAsync(string packageId, string repository, CancellationToken cancellationToken)
    {
        var apiUrl = new Uri($"https://api.github.com/repos/{repository}/releases/latest");
        using var response = await SendTrustedAsync(apiUrl, cancellationToken, "application/vnd.github+json");
        await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        using var json = await JsonDocument.ParseAsync(stream, cancellationToken: cancellationToken);
        var version = json.RootElement.GetProperty("tag_name").GetString() ?? "latest";
        var assets = json.RootElement.GetProperty("assets").EnumerateArray()
            .Select(asset => new
            {
                Name = asset.GetProperty("name").GetString() ?? string.Empty,
                Url = asset.GetProperty("browser_download_url").GetString() ?? string.Empty
            })
            .Where(asset => asset.Name.EndsWith(".zip", StringComparison.OrdinalIgnoreCase))
            .ToArray();
        var platform = OperatingSystem.IsWindows() ? "windows" : "linux";
        var selected = packageId switch
        {
            "counterstrikesharp" => assets.FirstOrDefault(asset => asset.Name.Contains("with-runtime", StringComparison.OrdinalIgnoreCase) && asset.Name.Contains(platform, StringComparison.OrdinalIgnoreCase)),
            "cs2kz" => assets.FirstOrDefault(asset => asset.Name.Contains(platform, StringComparison.OrdinalIgnoreCase)),
            _ => assets.FirstOrDefault(asset => asset.Name.Contains(platform, StringComparison.OrdinalIgnoreCase)) ?? assets.FirstOrDefault()
        };
        if (selected is null || !Uri.TryCreate(selected.Url, UriKind.Absolute, out var assetUrl) || assetUrl.Host != "github.com")
        {
            throw new InvalidOperationException($"The latest trusted release of '{packageId}' has no compatible ZIP asset for {platform}.");
        }

        return new PackageDownload(assetUrl, version);
    }

    private async Task DownloadAsync(Uri url, string destination, CancellationToken cancellationToken)
    {
        using var response = await SendTrustedAsync(url, cancellationToken, "application/octet-stream");
        if (response.Content.Headers.ContentLength is > MaximumDownloadBytes)
        {
            throw new InvalidDataException("The mod package download is larger than 256 MB.");
        }

        await using var input = await response.Content.ReadAsStreamAsync(cancellationToken);
        await using var output = new FileStream(destination, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, true);
        var buffer = new byte[81920];
        long total = 0;
        int read;
        while ((read = await input.ReadAsync(buffer, cancellationToken)) > 0)
        {
            total += read;
            if (total > MaximumDownloadBytes)
            {
                throw new InvalidDataException("The mod package download exceeded 256 MB.");
            }

            await output.WriteAsync(buffer.AsMemory(0, read), cancellationToken);
        }

        if (total < 4)
        {
            throw new InvalidDataException("The downloaded mod archive is empty.");
        }
    }

    private async Task<HttpResponseMessage> SendTrustedAsync(Uri url, CancellationToken cancellationToken, string? accept = null)
    {
        if (!IsTrustedDownloadHost(url.Host))
        {
            throw new InvalidOperationException("The managed package attempted to use an untrusted download host.");
        }

        using var request = new HttpRequestMessage(HttpMethod.Get, url);
        request.Headers.UserAgent.Add(new ProductInfoHeaderValue("DKayGameServerDock", "1.0"));
        if (accept is not null)
        {
            request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(accept));
        }

        var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
        if (response.RequestMessage?.RequestUri is not { } finalUri || !IsTrustedDownloadHost(finalUri.Host))
        {
            response.Dispose();
            throw new InvalidOperationException("The managed package redirected to an untrusted download host.");
        }

        response.EnsureSuccessStatusCode();
        return response;
    }

    private static bool IsTrustedDownloadHost(string host) => host.ToLowerInvariant() is
        "api.github.com" or
        "github.com" or
        "objects.githubusercontent.com" or
        "github-releases.githubusercontent.com" or
        "release-assets.githubusercontent.com" or
        "mms.alliedmods.net";

    private static string ResolvePayloadRoot(string stagingRoot)
    {
        var candidates = new[]
        {
            Path.Combine(stagingRoot, "game", "csgo"),
            Path.Combine(stagingRoot, "csgo"),
            stagingRoot
        }.Concat(Directory.GetDirectories(stagingRoot).SelectMany(directory => new[]
        {
            Path.Combine(directory, "game", "csgo"),
            Path.Combine(directory, "csgo"),
            directory
        }));

        return candidates.FirstOrDefault(candidate =>
                   Directory.Exists(Path.Combine(candidate, "addons")) ||
                   Directory.Exists(Path.Combine(candidate, "cfg")))
               ?? throw new InvalidDataException("The mod archive does not contain a CS2 addons or cfg payload.");
    }

    private static PackageDeployment ResolveDeployment(string packageId, string stagingRoot, string csgoRoot)
    {
        if (packageId == "cs2-tags")
        {
            var pluginAssembly = Directory
                .EnumerateFiles(stagingRoot, "CS2-Tags.dll", SearchOption.AllDirectories)
                .SingleOrDefault();
            if (pluginAssembly is null)
            {
                throw new InvalidDataException("The CS2-Tags archive does not contain CS2-Tags.dll.");
            }

            return new PackageDeployment(
                Path.GetDirectoryName(pluginAssembly)!,
                Path.Combine(csgoRoot, "addons", "counterstrikesharp", "plugins", "CS2-Tags"));
        }

        return new PackageDeployment(ResolvePayloadRoot(stagingRoot), csgoRoot);
    }

    private static async Task CopyPayloadAsync(string sourceRoot, string destinationRoot, CancellationToken cancellationToken)
    {
        var destination = Path.GetFullPath(destinationRoot) + Path.DirectorySeparatorChar;
        foreach (var sourceFile in Directory.EnumerateFiles(sourceRoot, "*", SearchOption.AllDirectories))
        {
            cancellationToken.ThrowIfCancellationRequested();
            var relative = Path.GetRelativePath(sourceRoot, sourceFile);
            var target = Path.GetFullPath(Path.Combine(destination, relative));
            if (!target.StartsWith(destination, StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidDataException("The staged mod payload escaped the CS2 directory.");
            }

            Directory.CreateDirectory(Path.GetDirectoryName(target)!);
            await using var input = new FileStream(sourceFile, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, true);
            await using var output = new FileStream(target, FileMode.Create, FileAccess.Write, FileShare.None, 81920, true);
            await input.CopyToAsync(output, cancellationToken);
        }
    }

    private static async Task PatchGameInfoAsync(GameServerInstance server, CancellationToken cancellationToken)
    {
        var gameInfoPath = Path.Combine(server.InstallDirectory, "game", "csgo", "gameinfo.gi");
        if (!File.Exists(gameInfoPath))
        {
            throw new InvalidOperationException("Metamod was extracted, but game/csgo/gameinfo.gi is missing.");
        }

        var lines = (await File.ReadAllLinesAsync(gameInfoPath, cancellationToken)).ToList();
        if (lines.Any(line => line.Contains("Game csgo/addons/metamod", StringComparison.OrdinalIgnoreCase)))
        {
            return;
        }

        var searchPaths = lines.FindIndex(line => line.Trim().Equals("SearchPaths", StringComparison.OrdinalIgnoreCase));
        var openingBrace = searchPaths < 0 ? -1 : lines.FindIndex(searchPaths + 1, line => line.Trim() == "{");
        if (openingBrace < 0)
        {
            throw new InvalidDataException("Could not safely locate SearchPaths in gameinfo.gi.");
        }

        var backupPath = $"{gameInfoPath}.dkay-original";
        if (!File.Exists(backupPath))
        {
            File.Copy(gameInfoPath, backupPath);
        }

        var indent = openingBrace + 1 < lines.Count
            ? lines[openingBrace + 1][..(lines[openingBrace + 1].Length - lines[openingBrace + 1].TrimStart().Length)]
            : "\t\t";
        lines.Insert(openingBrace + 1, $"{indent}Game csgo/addons/metamod");
        await WriteAllLinesAtomicallyAsync(gameInfoPath, lines, cancellationToken);
    }

    private static string FormatCfgValue(string value)
    {
        if (NumericValuePattern().IsMatch(value))
        {
            return value;
        }

        var escaped = value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
        return $"\"{escaped}\"";
    }

    private static ModeDocument ReadModeDocument(GameServerInstance server)
    {
        var path = GetModeDocumentPath(server);
        if (!File.Exists(path))
        {
            return new ModeDocument(null, []);
        }

        try
        {
            return JsonSerializer.Deserialize<ModeDocument>(File.ReadAllText(path), FileJsonOptions)
                   ?? new ModeDocument(null, []);
        }
        catch (JsonException)
        {
            return new ModeDocument(null, []);
        }
    }

    private static PackageMarker ReadPackageMarker(GameServerInstance server, string packageId)
    {
        var path = GetPackageMarkerPath(server, packageId);
        if (!File.Exists(path))
        {
            return new PackageMarker(false, null, null);
        }

        try
        {
            return JsonSerializer.Deserialize<PackageMarker>(File.ReadAllText(path), FileJsonOptions)
                   ?? new PackageMarker(false, null, null);
        }
        catch (JsonException)
        {
            return new PackageMarker(false, null, null);
        }
    }

    private static Task WritePackageMarkerAsync(
        GameServerInstance server,
        PackageMarker marker,
        string packageId,
        CancellationToken cancellationToken) =>
        WriteJsonAtomicallyAsync(GetPackageMarkerPath(server, packageId), marker, cancellationToken);

    private static string GetCsgoRoot(GameServerInstance server) => Path.Combine(server.InstallDirectory, "game", "csgo");
    private static string GetCfgRoot(GameServerInstance server) => Path.Combine(GetCsgoRoot(server), "cfg");
    private static string GetModeDocumentPath(GameServerInstance server) => Path.Combine(GetCfgRoot(server), "dkay", "modes.json");
    private static string GetPackageMarkerPath(GameServerInstance server, string packageId) =>
        Path.Combine(GetCsgoRoot(server), "addons", ".dkay", $"{packageId}.json");

    private static async Task WriteAllLinesAtomicallyAsync(string path, IEnumerable<string> lines, CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        var temporary = $"{path}.{Guid.NewGuid():N}.tmp";
        await File.WriteAllLinesAsync(temporary, lines.ToArray(), new UTF8Encoding(false), cancellationToken);
        File.Move(temporary, path, true);
    }

    private static async Task WriteJsonAtomicallyAsync<T>(string path, T value, CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        var temporary = $"{path}.{Guid.NewGuid():N}.tmp";
        await using (var stream = new FileStream(temporary, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, true))
        {
            await JsonSerializer.SerializeAsync(stream, value, FileJsonOptions, cancellationToken);
        }

        File.Move(temporary, path, true);
    }

    private sealed record ModeDocument(string? ActiveProfileId, IReadOnlyList<Cs2ModeProfile> Profiles);
    private sealed record PackageMarker(bool Installed, string? Version, DateTimeOffset? InstalledAt);
    private sealed record PackageSource(PackageSourceKind Kind, string? Repository);
    private sealed record PackageDownload(Uri Url, string Version);
    private sealed record PackageDeployment(string SourceRoot, string DestinationRoot);

    private enum PackageSourceKind
    {
        GitHubRelease,
        MetamodSnapshot
    }

    [GeneratedRegex("^mmsource-[A-Za-z0-9._-]+-(windows|linux)\\.zip$", RegexOptions.CultureInvariant | RegexOptions.IgnoreCase)]
    private static partial Regex MetamodFilePattern();

    [GeneratedRegex("^-?[0-9]+(?:\\.[0-9]+)?$", RegexOptions.CultureInvariant)]
    private static partial Regex NumericValuePattern();
}
