<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DKay.GameServerDock.Application/DKay.GameServerDock.Application.csproj" />
    <ProjectReference Include="../../src/DKay.GameServerDock.Domain/DKay.GameServerDock.Domain.csproj" />
    <ProjectReference Include="../../src/DKay.GameServerDock.Infrastructure/DKay.GameServerDock.Infrastructure.csproj" />
  </ItemGroup>
</Project>
